language: python
python:
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.7
  - DJANGO=1.4.6
  - DJANGO=1.5.2
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libldap2-dev libsasl2-dev
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q python-ldap --use-mirrors
script: python manage.py test ldapdb
