language: python
python:
  - "2.7"
env:
  - DJANGO=Django==1.2.7
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6.1
install:
  - pip install -q $DJANGO python-ldap mockldap --use-mirrors
script: python manage.py test ldapdb examples
